before:
  hooks:
    - go mod tidy
builds:
  -
    id: "cftsmt"
    main: ./cmd/cftsmt/main.go
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
